# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(verbose_name='is published')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email_id', models.EmailField(blank=True, max_length=30)),
                ('mobile_number', models.IntegerField(unique=True)),
                ('year', models.CharField(choices=[('1', 'FIRST YEAR'), ('2', 'SECOND YEAR'), ('3', 'THIRD YEAR'), ('4', 'FOURTH YEAR')], max_length=1)),
                ('hostel_name', models.CharField(choices=[('Y', 'YASHODHARA BHAVAN'), ('K', 'KALPANA BHAVAN'), ('V', 'VRINDAVAN BHAVAN'), ('S', 'SAKET BHAVAN'), ('P', 'PANCHAVATI BHAVAN'), ('J', 'JAYBHARAT BHAVAN')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.Question'),
        ),
    ]
