# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-11 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=False),
        ),
    ]
